### ISSUE TITLE
DAL缺失

### ISSUE THREAD

**Issue by bearDream** [BitInit/pnd#2]
项目提供了mysql的可选项，但是没有找到数据库的dal，这样还是无法运行呀

**Comment by BitInit** [comment]
您好！测试了一下，release里面发布的预览版设置数据库为mysql时无效，这应该是个bug，按照设计会自动加载 conf/META-INFO/schema-mysql.sql 文件自动创建mysql数据库表的。后面会修复这个问题。感谢关注该项目！！！

**Comment by bearDream** [comment]
好的～
